[2023-08-29T03:02:03.575+0000] {processor.py:157} INFO - Started process (PID=17981) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:02:03.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:02:03.578+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:02:03.577+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:02:04.048+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:02:04.046+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:02:04.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:02:04.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.499 seconds
[2023-08-29T03:02:29.177+0000] {processor.py:157} INFO - Started process (PID=18027) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:02:29.179+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:02:29.180+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:02:29.180+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:02:29.699+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:02:29.696+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:02:29.700+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:02:29.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.545 seconds
[2023-08-29T03:03:00.416+0000] {processor.py:157} INFO - Started process (PID=18084) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:03:00.417+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:03:00.419+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:03:00.418+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:03:00.959+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:03:00.956+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:03:00.960+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:03:00.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.570 seconds
[2023-08-29T03:03:31.158+0000] {processor.py:157} INFO - Started process (PID=18144) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:03:31.160+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:03:31.161+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:03:31.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:03:31.690+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:03:31.688+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:03:31.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:03:31.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.559 seconds
[2023-08-29T03:04:02.212+0000] {processor.py:157} INFO - Started process (PID=18201) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:04:02.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:04:02.215+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:04:02.215+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:04:02.717+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:04:02.715+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:04:02.718+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:04:02.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.529 seconds
[2023-08-29T03:04:32.836+0000] {processor.py:157} INFO - Started process (PID=18261) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:04:32.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:04:32.839+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:04:32.839+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:04:33.398+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:04:33.396+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:04:33.418+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:04:33.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.608 seconds
[2023-08-29T03:05:03.884+0000] {processor.py:157} INFO - Started process (PID=18318) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:05:03.886+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:05:03.887+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:05:03.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:05:04.348+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:05:04.346+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:05:04.348+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:05:04.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.483 seconds
[2023-08-29T03:05:35.272+0000] {processor.py:157} INFO - Started process (PID=18377) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:05:35.284+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:05:35.285+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:05:35.285+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:05:35.793+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:05:35.791+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:05:35.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:05:35.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.543 seconds
[2023-08-29T03:06:05.904+0000] {processor.py:157} INFO - Started process (PID=18436) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:06:05.905+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:06:05.907+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:06:05.906+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:06:06.360+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:06:06.358+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:06:06.361+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:06:06.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.477 seconds
[2023-08-29T03:06:36.462+0000] {processor.py:157} INFO - Started process (PID=18491) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:06:36.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:06:36.465+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:06:36.465+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:06:36.939+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:06:36.937+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:06:36.940+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:06:36.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.501 seconds
[2023-08-29T03:07:07.178+0000] {processor.py:157} INFO - Started process (PID=18550) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:07:07.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:07:07.181+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:07:07.181+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:07:07.620+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:07:07.618+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:07:07.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:07:07.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.461 seconds
[2023-08-29T03:07:38.006+0000] {processor.py:157} INFO - Started process (PID=18608) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:07:38.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:07:38.009+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:07:38.009+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:07:38.558+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:07:38.555+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:07:38.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:07:38.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.578 seconds
[2023-08-29T03:08:09.246+0000] {processor.py:157} INFO - Started process (PID=18665) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:08:09.247+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:08:09.249+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:08:09.249+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:08:09.751+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:08:09.749+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:08:09.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:08:09.770+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.530 seconds
[2023-08-29T03:08:39.801+0000] {processor.py:157} INFO - Started process (PID=18723) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:08:39.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:08:39.804+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:08:39.803+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:08:40.294+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:08:40.292+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:08:40.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:08:40.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.518 seconds
[2023-08-29T03:09:10.721+0000] {processor.py:157} INFO - Started process (PID=18780) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:09:10.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:09:10.723+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:09:10.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:09:11.167+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:09:11.165+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:09:11.168+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:09:11.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.470 seconds
[2023-08-29T03:09:41.544+0000] {processor.py:157} INFO - Started process (PID=18837) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:09:41.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:09:41.548+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:09:41.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:09:42.125+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:09:42.123+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:09:42.125+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:09:42.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.606 seconds
[2023-08-29T03:10:12.571+0000] {processor.py:157} INFO - Started process (PID=18895) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:12.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:10:12.574+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:10:12.573+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:13.128+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:10:13.126+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:10:13.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:13.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.582 seconds
[2023-08-29T03:10:14.036+0000] {processor.py:157} INFO - Started process (PID=18900) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:14.038+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:10:14.039+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:10:14.039+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:14.570+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:10:14.568+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:10:14.571+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:14.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.558 seconds
[2023-08-29T03:10:45.381+0000] {processor.py:157} INFO - Started process (PID=18958) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:45.383+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:10:45.384+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:10:45.384+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:45.868+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:10:45.866+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:10:45.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:10:45.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.510 seconds
[2023-08-29T03:11:16.327+0000] {processor.py:157} INFO - Started process (PID=19015) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:11:16.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:11:16.333+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:11:16.332+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:11:17.099+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:11:17.097+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:11:17.101+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:11:17.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.820 seconds
[2023-08-29T03:11:47.445+0000] {processor.py:157} INFO - Started process (PID=19072) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:11:47.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:11:47.448+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:11:47.448+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:11:47.974+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:11:47.972+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:11:47.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:11:48.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.560 seconds
[2023-08-29T03:12:18.127+0000] {processor.py:157} INFO - Started process (PID=19132) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:12:18.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:12:18.130+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:12:18.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:12:18.617+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:12:18.615+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:12:18.618+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:12:18.636+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.514 seconds
[2023-08-29T03:12:48.942+0000] {processor.py:157} INFO - Started process (PID=19186) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:12:48.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:12:48.945+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:12:48.945+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:12:49.501+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:12:49.498+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:12:49.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:12:49.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.586 seconds
[2023-08-29T03:13:19.663+0000] {processor.py:157} INFO - Started process (PID=19247) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:13:19.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:13:19.666+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:13:19.666+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:13:20.247+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:13:20.244+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:13:20.248+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:13:20.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.610 seconds
[2023-08-29T03:13:50.460+0000] {processor.py:157} INFO - Started process (PID=19304) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:13:50.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:13:50.463+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:13:50.462+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:13:50.993+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:13:50.991+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:13:50.995+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:13:51.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.560 seconds
[2023-08-29T03:14:21.488+0000] {processor.py:157} INFO - Started process (PID=19362) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:14:21.489+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:14:21.491+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:14:21.490+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:14:22.075+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:14:22.073+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:14:22.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:14:22.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.636 seconds
[2023-08-29T03:14:52.353+0000] {processor.py:157} INFO - Started process (PID=19416) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:14:52.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:14:52.356+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:14:52.356+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:14:52.877+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:14:52.875+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:14:52.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:14:52.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.548 seconds
[2023-08-29T03:15:23.005+0000] {processor.py:157} INFO - Started process (PID=19476) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:15:23.007+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:15:23.008+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:15:23.008+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:15:23.602+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:15:23.599+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:15:23.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:15:23.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.626 seconds
[2023-08-29T03:15:53.908+0000] {processor.py:157} INFO - Started process (PID=19535) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:15:53.910+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:15:53.911+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:15:53.911+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:15:54.511+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:15:54.509+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:15:54.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:15:54.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.634 seconds
[2023-08-29T03:16:24.662+0000] {processor.py:157} INFO - Started process (PID=19592) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:16:24.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:16:24.665+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:16:24.665+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:16:25.162+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:16:25.159+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:16:25.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:16:25.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.527 seconds
[2023-08-29T03:16:56.162+0000] {processor.py:157} INFO - Started process (PID=19649) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:16:56.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:16:56.165+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:16:56.165+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:16:56.643+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:16:56.641+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:16:56.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:16:56.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.503 seconds
[2023-08-29T03:17:27.474+0000] {processor.py:157} INFO - Started process (PID=19712) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:17:27.475+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:17:27.477+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:17:27.476+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:17:27.986+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:17:27.984+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:17:27.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:17:28.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.538 seconds
[2023-08-29T03:17:58.975+0000] {processor.py:157} INFO - Started process (PID=19769) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:17:58.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:17:58.978+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:17:58.978+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:17:59.484+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:17:59.482+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:17:59.485+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:17:59.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.534 seconds
[2023-08-29T03:18:30.369+0000] {processor.py:157} INFO - Started process (PID=19826) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:18:30.371+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:18:30.372+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:18:30.372+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:18:30.735+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:18:30.731+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:18:30.736+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:18:30.757+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.393 seconds
[2023-08-29T03:19:01.145+0000] {processor.py:157} INFO - Started process (PID=19883) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:19:01.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:19:01.148+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:19:01.147+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:19:01.580+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:19:01.574+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:19:01.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:19:01.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.497 seconds
[2023-08-29T03:19:31.720+0000] {processor.py:157} INFO - Started process (PID=19940) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:19:31.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:19:31.724+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:19:31.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:19:32.166+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:19:32.161+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:19:32.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:19:32.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.473 seconds
[2023-08-29T03:20:02.323+0000] {processor.py:157} INFO - Started process (PID=19997) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:20:02.325+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:20:02.326+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:20:02.326+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:20:02.783+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:20:02.778+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:20:02.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:20:02.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.486 seconds
[2023-08-29T03:20:33.598+0000] {processor.py:157} INFO - Started process (PID=20055) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:20:33.600+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:20:33.601+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:20:33.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:20:34.013+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:20:34.005+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:20:34.014+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:20:34.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.442 seconds
[2023-08-29T03:21:04.213+0000] {processor.py:157} INFO - Started process (PID=20112) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:21:04.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:21:04.216+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:21:04.216+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:21:04.619+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:21:04.615+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:21:04.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:21:04.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.438 seconds
[2023-08-29T03:21:34.813+0000] {processor.py:157} INFO - Started process (PID=20169) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:21:34.814+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:21:34.816+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:21:34.815+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:21:35.232+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:21:35.227+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:21:35.233+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:21:35.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.450 seconds
[2023-08-29T03:22:05.450+0000] {processor.py:157} INFO - Started process (PID=20226) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:22:05.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:22:05.453+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:22:05.453+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:22:05.854+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:22:05.850+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:22:05.855+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:22:05.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.436 seconds
[2023-08-29T03:22:36.040+0000] {processor.py:157} INFO - Started process (PID=20285) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:22:36.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:22:36.043+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:22:36.043+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:22:36.451+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:22:36.447+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:22:36.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:22:36.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.440 seconds
[2023-08-29T03:23:06.593+0000] {processor.py:157} INFO - Started process (PID=20344) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:23:06.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:23:06.601+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:23:06.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:23:06.995+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:23:06.992+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:23:06.997+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:23:07.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.430 seconds
[2023-08-29T03:23:37.810+0000] {processor.py:157} INFO - Started process (PID=20402) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:23:37.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:23:37.813+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:23:37.812+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:23:38.195+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:23:38.191+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:23:38.196+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:23:38.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.414 seconds
[2023-08-29T03:24:09.079+0000] {processor.py:157} INFO - Started process (PID=20459) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:24:09.083+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:24:09.084+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:24:09.084+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:24:09.476+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:24:09.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:24:09.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:24:09.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.424 seconds
[2023-08-29T03:24:40.452+0000] {processor.py:157} INFO - Started process (PID=20516) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:24:40.454+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:24:40.455+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:24:40.455+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:24:40.845+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:24:40.841+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:24:40.847+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:24:40.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.421 seconds
[2023-08-29T03:25:11.734+0000] {processor.py:157} INFO - Started process (PID=20573) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:25:11.736+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:25:11.737+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:25:11.737+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:25:12.119+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:25:12.116+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:25:12.120+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:25:12.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.415 seconds
[2023-08-29T03:25:43.111+0000] {processor.py:157} INFO - Started process (PID=20630) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:25:43.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:25:43.114+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:25:43.113+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:25:43.487+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:25:43.483+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:25:43.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:25:43.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.406 seconds
[2023-08-29T03:26:14.447+0000] {processor.py:157} INFO - Started process (PID=20687) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:26:14.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:26:14.450+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:26:14.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:26:14.834+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:26:14.830+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:26:14.835+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:26:14.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.415 seconds
[2023-08-29T03:26:44.891+0000] {processor.py:157} INFO - Started process (PID=20744) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:26:44.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:26:44.894+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:26:44.894+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:26:45.290+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:26:45.286+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:26:45.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:26:45.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.431 seconds
[2023-08-29T03:27:15.561+0000] {processor.py:157} INFO - Started process (PID=20801) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:27:15.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:27:15.564+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:27:15.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:27:15.964+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:27:15.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:27:15.965+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:27:15.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.432 seconds
[2023-08-29T03:27:46.023+0000] {processor.py:157} INFO - Started process (PID=20858) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:27:46.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:27:46.026+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:27:46.026+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:27:46.414+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:27:46.410+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:27:46.418+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:27:46.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.421 seconds
[2023-08-29T03:28:16.540+0000] {processor.py:157} INFO - Started process (PID=20915) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:28:16.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:28:16.543+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:28:16.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:28:16.924+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:28:16.920+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:28:16.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:28:16.947+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.411 seconds
[2023-08-29T03:28:47.142+0000] {processor.py:157} INFO - Started process (PID=20972) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:28:47.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:28:47.145+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:28:47.145+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:28:47.570+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:28:47.565+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:28:47.571+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:28:47.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.458 seconds
[2023-08-29T03:29:17.695+0000] {processor.py:157} INFO - Started process (PID=21029) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:29:17.697+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:29:17.698+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:29:17.698+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:29:18.093+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:29:18.089+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:29:18.094+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:29:18.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.431 seconds
[2023-08-29T03:29:48.424+0000] {processor.py:157} INFO - Started process (PID=21086) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:29:48.426+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:29:48.427+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:29:48.427+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:29:48.815+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:29:48.811+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:29:48.816+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:29:48.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.420 seconds
[2023-08-29T03:30:18.971+0000] {processor.py:157} INFO - Started process (PID=21143) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:30:18.973+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:30:18.974+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:30:18.974+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:30:19.357+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:30:19.353+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:30:19.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:30:19.382+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.418 seconds
[2023-08-29T03:30:49.487+0000] {processor.py:157} INFO - Started process (PID=21200) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:30:49.489+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:30:49.490+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:30:49.490+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:30:49.876+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:30:49.872+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:30:49.877+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:30:49.898+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.416 seconds
[2023-08-29T03:31:20.401+0000] {processor.py:157} INFO - Started process (PID=21257) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:31:20.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:31:20.405+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:31:20.404+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:31:20.857+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:31:20.853+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:31:20.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:31:20.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.490 seconds
[2023-08-29T03:31:51.790+0000] {processor.py:157} INFO - Started process (PID=21314) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:31:51.791+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:31:51.792+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:31:51.792+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:31:52.175+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:31:52.171+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:31:52.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:31:52.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.413 seconds
[2023-08-29T03:32:22.338+0000] {processor.py:157} INFO - Started process (PID=21371) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:32:22.340+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:32:22.341+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:32:22.341+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:32:22.725+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:32:22.721+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:32:22.726+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:32:22.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.421 seconds
[2023-08-29T03:32:52.828+0000] {processor.py:157} INFO - Started process (PID=21428) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:32:52.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:32:52.830+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:32:52.830+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:32:53.213+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:32:53.209+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:32:53.214+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:32:53.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.413 seconds
[2023-08-29T03:33:23.569+0000] {processor.py:157} INFO - Started process (PID=21485) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:33:23.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:33:23.573+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:33:23.572+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:33:23.954+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:33:23.950+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:33:23.955+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:33:23.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.415 seconds
[2023-08-29T03:33:54.043+0000] {processor.py:157} INFO - Started process (PID=21542) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:33:54.045+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:33:54.047+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:33:54.047+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:33:54.497+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:33:54.493+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:33:54.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:33:54.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.485 seconds
[2023-08-29T03:34:24.864+0000] {processor.py:157} INFO - Started process (PID=21599) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:34:24.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:34:24.867+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:34:24.867+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:34:25.250+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:34:25.246+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:34:25.251+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:34:25.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.417 seconds
[2023-08-29T03:34:55.549+0000] {processor.py:157} INFO - Started process (PID=21656) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:34:55.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:34:55.552+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:34:55.551+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:34:55.924+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:34:55.920+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:34:55.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:34:55.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.404 seconds
[2023-08-29T03:35:26.487+0000] {processor.py:157} INFO - Started process (PID=21713) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:35:26.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:35:26.491+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:35:26.491+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:35:26.985+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:35:26.981+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:35:26.986+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:35:27.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.530 seconds
[2023-08-29T03:35:57.084+0000] {processor.py:157} INFO - Started process (PID=21770) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:35:57.085+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:35:57.087+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:35:57.087+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:35:57.479+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:35:57.476+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:35:57.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:35:57.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.427 seconds
[2023-08-29T03:36:27.870+0000] {processor.py:157} INFO - Started process (PID=21828) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:36:27.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:36:27.873+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:36:27.873+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:36:28.245+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:36:28.242+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:36:28.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:36:28.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.400 seconds
[2023-08-29T03:36:58.348+0000] {processor.py:157} INFO - Started process (PID=21889) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:36:58.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:36:58.350+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:36:58.350+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:36:58.686+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:36:58.683+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:36:58.687+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:36:58.704+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.362 seconds
[2023-08-29T03:37:28.840+0000] {processor.py:157} INFO - Started process (PID=21947) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:37:28.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:37:28.843+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:37:28.842+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:37:29.155+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:37:29.152+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:37:29.156+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:37:29.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.339 seconds
[2023-08-29T03:37:59.739+0000] {processor.py:157} INFO - Started process (PID=22003) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:37:59.741+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:37:59.743+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:37:59.742+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:38:00.084+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:38:00.080+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:38:00.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:38:00.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.371 seconds
[2023-08-29T03:38:30.147+0000] {processor.py:157} INFO - Started process (PID=22068) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:38:30.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:38:30.150+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:38:30.150+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:38:30.468+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:38:30.465+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:38:30.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:38:30.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.347 seconds
[2023-08-29T03:39:00.760+0000] {processor.py:157} INFO - Started process (PID=22124) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:39:00.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:39:00.768+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:39:00.767+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:39:01.232+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:39:01.227+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:39:01.233+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:39:01.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.502 seconds
[2023-08-29T03:39:32.148+0000] {processor.py:157} INFO - Started process (PID=22183) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:39:32.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:39:32.152+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:39:32.152+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:39:32.840+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:39:32.835+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:39:32.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:39:32.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.838 seconds
[2023-08-29T03:40:03.853+0000] {processor.py:157} INFO - Started process (PID=22240) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:40:03.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:40:03.856+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:40:03.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:40:04.367+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:40:04.363+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:40:04.368+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:40:04.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.544 seconds
[2023-08-29T03:40:35.179+0000] {processor.py:157} INFO - Started process (PID=22297) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:40:35.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:40:35.182+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:40:35.182+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:40:35.599+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:40:35.595+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:40:35.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:40:35.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.476 seconds
[2023-08-29T03:41:05.734+0000] {processor.py:157} INFO - Started process (PID=22357) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:41:05.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:41:05.736+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:41:05.736+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:41:06.116+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:41:06.112+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:41:06.117+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:41:06.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.415 seconds
[2023-08-29T03:41:36.495+0000] {processor.py:157} INFO - Started process (PID=22411) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:41:36.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:41:36.498+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:41:36.498+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:41:36.911+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:41:36.907+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:41:36.912+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:41:36.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.445 seconds
[2023-08-29T03:42:07.295+0000] {processor.py:157} INFO - Started process (PID=22468) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:42:07.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:42:07.298+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:42:07.297+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:42:07.706+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:42:07.703+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:42:07.708+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:42:07.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.443 seconds
[2023-08-29T03:42:38.073+0000] {processor.py:157} INFO - Started process (PID=22525) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:42:38.074+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:42:38.076+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:42:38.075+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:42:38.487+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:42:38.483+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:42:38.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:42:38.509+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.442 seconds
[2023-08-29T03:43:08.892+0000] {processor.py:157} INFO - Started process (PID=22582) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:43:08.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:43:08.896+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:43:08.895+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:43:09.310+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:43:09.306+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:43:09.311+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:43:09.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.449 seconds
[2023-08-29T03:43:40.059+0000] {processor.py:157} INFO - Started process (PID=22640) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:43:40.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:43:40.062+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:43:40.062+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:43:40.433+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:43:40.430+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:43:40.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:43:40.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.399 seconds
[2023-08-29T03:44:10.884+0000] {processor.py:157} INFO - Started process (PID=22697) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:44:10.886+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:44:10.887+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:44:10.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:44:11.257+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:44:11.254+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:44:11.258+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:44:11.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.400 seconds
[2023-08-29T03:44:41.320+0000] {processor.py:157} INFO - Started process (PID=22754) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:44:41.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:44:41.323+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:44:41.322+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:44:41.694+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:44:41.691+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:44:41.695+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:44:41.714+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.399 seconds
[2023-08-29T03:45:11.746+0000] {processor.py:157} INFO - Started process (PID=22811) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:45:11.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:45:11.748+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:45:11.748+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:45:12.111+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:45:12.107+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:45:12.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:45:12.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.390 seconds
[2023-08-29T03:45:42.238+0000] {processor.py:157} INFO - Started process (PID=22868) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:45:42.239+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:45:42.241+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:45:42.240+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:45:42.602+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:45:42.599+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:45:42.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:45:42.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.390 seconds
[2023-08-29T03:46:12.678+0000] {processor.py:157} INFO - Started process (PID=22925) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:46:12.679+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T03:46:12.681+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:46:12.680+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:46:13.054+0000] {logging_mixin.py:151} INFO - [2023-08-29T03:46:13.050+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T03:46:13.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T03:46:13.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.403 seconds
[2023-08-29T04:02:06.606+0000] {processor.py:157} INFO - Started process (PID=22988) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:02:06.608+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T04:02:06.609+0000] {logging_mixin.py:151} INFO - [2023-08-29T04:02:06.609+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:02:07.043+0000] {logging_mixin.py:151} INFO - [2023-08-29T04:02:07.039+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T04:02:07.044+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:02:07.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.464 seconds
[2023-08-29T04:46:38.515+0000] {processor.py:157} INFO - Started process (PID=23045) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:46:38.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T04:46:38.520+0000] {logging_mixin.py:151} INFO - [2023-08-29T04:46:38.520+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:46:39.042+0000] {logging_mixin.py:151} INFO - [2023-08-29T04:46:39.038+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T04:46:39.043+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:46:39.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.560 seconds
[2023-08-29T04:47:09.548+0000] {processor.py:157} INFO - Started process (PID=23103) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:47:09.554+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T04:47:09.561+0000] {logging_mixin.py:151} INFO - [2023-08-29T04:47:09.559+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:47:11.236+0000] {logging_mixin.py:151} INFO - [2023-08-29T04:47:11.221+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T04:47:11.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T04:47:11.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.798 seconds
[2023-08-29T05:07:03.333+0000] {processor.py:157} INFO - Started process (PID=23126) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:07:03.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T05:07:03.339+0000] {logging_mixin.py:151} INFO - [2023-08-29T05:07:03.339+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:07:04.355+0000] {logging_mixin.py:151} INFO - [2023-08-29T05:07:04.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T05:07:04.356+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:07:04.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.076 seconds
[2023-08-29T05:07:34.958+0000] {processor.py:157} INFO - Started process (PID=23186) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:07:34.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T05:07:34.961+0000] {logging_mixin.py:151} INFO - [2023-08-29T05:07:34.960+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:07:35.458+0000] {logging_mixin.py:151} INFO - [2023-08-29T05:07:35.456+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T05:07:35.459+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:07:35.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.524 seconds
[2023-08-29T05:08:06.331+0000] {processor.py:157} INFO - Started process (PID=23246) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T05:08:06.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T05:08:06.334+0000] {logging_mixin.py:151} INFO - [2023-08-29T05:08:06.334+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:03:25.988+0000] {logging_mixin.py:151} INFO - [2023-08-29T08:03:25.625+0000] {timeout.py:68} ERROR - Process timed out, PID: 23246
[2023-08-29T08:03:26.035+0000] {logging_mixin.py:151} INFO - [2023-08-29T08:03:26.006+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/__init__.py", line 138, in <module>
    from pandas import testing
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/testing.py", line 6, in <module>
    from pandas._testing import (
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/_testing/__init__.py", line 58, in <module>
    from pandas._testing._io import (
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/_testing/_io.py", line 24, in <module>
    from pandas._testing._random import rands
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1540, in find_spec
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/sensor_plot_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.0/best-practices.html#reducing-dag-complexity, PID: 23246
[2023-08-29T08:03:26.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:03:26.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 10519.509 seconds
[2023-08-29T08:08:09.595+0000] {processor.py:157} INFO - Started process (PID=23308) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:08:09.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T08:08:09.599+0000] {logging_mixin.py:151} INFO - [2023-08-29T08:08:09.598+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:08:10.314+0000] {logging_mixin.py:151} INFO - [2023-08-29T08:08:10.311+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T08:08:10.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:08:10.333+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.754 seconds
[2023-08-29T08:08:41.085+0000] {processor.py:157} INFO - Started process (PID=23375) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:08:41.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T08:08:41.095+0000] {logging_mixin.py:151} INFO - [2023-08-29T08:08:41.094+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:08:43.346+0000] {logging_mixin.py:151} INFO - [2023-08-29T08:08:43.336+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T08:08:43.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T08:08:43.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 2.364 seconds
[2023-08-29T09:45:08.624+0000] {processor.py:157} INFO - Started process (PID=23421) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T09:45:08.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T09:45:08.633+0000] {logging_mixin.py:151} INFO - [2023-08-29T09:45:08.632+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T09:45:09.856+0000] {logging_mixin.py:151} INFO - [2023-08-29T09:45:09.853+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T09:45:09.857+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T09:45:09.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.276 seconds
[2023-08-29T17:09:19.276+0000] {processor.py:157} INFO - Started process (PID=23479) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T17:09:19.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T17:09:19.288+0000] {logging_mixin.py:151} INFO - [2023-08-29T17:09:19.285+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T17:09:20.746+0000] {logging_mixin.py:151} INFO - [2023-08-29T17:09:20.743+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T17:09:20.747+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T17:09:20.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.517 seconds
[2023-08-29T21:55:53.232+0000] {processor.py:157} INFO - Started process (PID=23536) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:55:53.234+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:55:53.236+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:55:53.236+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:55:54.330+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:55:54.322+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:55:54.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:55:54.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.133 seconds
[2023-08-29T21:56:25.148+0000] {processor.py:157} INFO - Started process (PID=23605) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:56:25.161+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:56:25.163+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:56:25.162+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:56:25.889+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:56:25.886+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:56:25.903+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:56:25.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.788 seconds
[2023-08-29T21:56:56.309+0000] {processor.py:157} INFO - Started process (PID=23662) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:56:56.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:56:56.312+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:56:56.312+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:56:56.827+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:56:56.825+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:56:56.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:56:56.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.542 seconds
[2023-08-29T21:57:26.945+0000] {processor.py:157} INFO - Started process (PID=23723) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:57:26.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:57:26.947+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:57:26.947+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:57:27.456+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:57:27.454+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:57:27.457+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:57:27.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.535 seconds
[2023-08-29T21:57:57.534+0000] {processor.py:157} INFO - Started process (PID=23784) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:57:57.536+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:57:57.537+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:57:57.536+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:57:58.048+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:57:58.046+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:57:58.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:57:58.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.537 seconds
[2023-08-29T21:58:28.150+0000] {processor.py:157} INFO - Started process (PID=23845) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:58:28.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:58:28.153+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:58:28.153+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:58:28.616+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:58:28.614+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:58:28.617+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:58:28.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.487 seconds
[2023-08-29T21:58:58.724+0000] {processor.py:157} INFO - Started process (PID=23900) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:58:58.726+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:58:58.727+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:58:58.727+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:58:59.227+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:58:59.225+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:58:59.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:58:59.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.526 seconds
[2023-08-29T21:59:29.563+0000] {processor.py:157} INFO - Started process (PID=23958) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:59:29.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T21:59:29.566+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:59:29.566+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:59:30.110+0000] {logging_mixin.py:151} INFO - [2023-08-29T21:59:30.108+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T21:59:30.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T21:59:30.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.567 seconds
[2023-08-29T22:00:00.723+0000] {processor.py:157} INFO - Started process (PID=24016) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:00:00.724+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:00:00.726+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:00:00.726+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:00:01.857+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:00:01.854+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:00:01.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:00:01.880+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.162 seconds
[2023-08-29T22:00:32.170+0000] {processor.py:157} INFO - Started process (PID=24073) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:00:32.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:00:32.173+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:00:32.173+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:00:32.667+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:00:32.665+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:00:32.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:00:32.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.520 seconds
[2023-08-29T22:01:02.948+0000] {processor.py:157} INFO - Started process (PID=24134) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:01:02.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:01:02.951+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:01:02.951+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:01:03.390+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:01:03.388+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:01:03.390+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:01:03.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.462 seconds
[2023-08-29T22:01:33.716+0000] {processor.py:157} INFO - Started process (PID=24187) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:01:33.717+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:01:33.719+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:01:33.718+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:01:34.226+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:01:34.223+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:01:34.227+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:01:34.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.537 seconds
[2023-08-29T22:02:04.686+0000] {processor.py:157} INFO - Started process (PID=24244) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:02:04.688+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:02:04.689+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:02:04.689+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:02:05.241+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:02:05.239+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:02:05.242+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:02:05.262+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.581 seconds
[2023-08-29T22:02:35.595+0000] {processor.py:157} INFO - Started process (PID=24301) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:02:35.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:02:35.597+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:02:35.597+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:02:36.110+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:02:36.108+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:02:36.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:02:36.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.539 seconds
[2023-08-29T22:03:06.720+0000] {processor.py:157} INFO - Started process (PID=24358) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:03:06.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:03:06.723+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:03:06.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:03:07.223+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:03:07.221+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:03:07.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:03:07.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.528 seconds
[2023-08-29T22:03:37.513+0000] {processor.py:157} INFO - Started process (PID=24419) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:03:37.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:03:37.516+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:03:37.516+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:03:37.966+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:03:37.964+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:03:37.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:03:37.984+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.475 seconds
[2023-08-29T22:04:08.738+0000] {processor.py:157} INFO - Started process (PID=24476) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:04:08.740+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:04:08.741+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:04:08.741+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:04:09.260+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:04:09.257+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:04:09.261+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:04:09.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.548 seconds
[2023-08-29T22:04:39.350+0000] {processor.py:157} INFO - Started process (PID=24537) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:04:39.352+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:04:39.353+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:04:39.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:04:39.891+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:04:39.887+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:04:39.892+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:04:39.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.566 seconds
[2023-08-29T22:05:10.065+0000] {processor.py:157} INFO - Started process (PID=24598) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:05:10.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:05:10.067+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:05:10.067+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:05:10.527+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:05:10.525+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:05:10.527+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:05:10.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.484 seconds
[2023-08-29T22:05:41.180+0000] {processor.py:157} INFO - Started process (PID=24655) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:05:41.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:05:41.184+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:05:41.183+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:05:41.685+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:05:41.683+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:05:41.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:05:41.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.529 seconds
[2023-08-29T22:06:12.022+0000] {processor.py:157} INFO - Started process (PID=24712) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:06:12.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:06:12.025+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:06:12.025+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:06:12.538+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:06:12.536+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:06:12.539+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:06:12.558+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.541 seconds
[2023-08-29T22:06:43.058+0000] {processor.py:157} INFO - Started process (PID=24769) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:06:43.060+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:06:43.062+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:06:43.061+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:06:43.619+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:06:43.616+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:06:43.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:06:43.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.587 seconds
[2023-08-29T22:07:13.929+0000] {processor.py:157} INFO - Started process (PID=24830) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:07:13.931+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:07:13.932+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:07:13.931+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:07:14.524+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:07:14.521+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:07:14.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:07:14.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.622 seconds
[2023-08-29T22:07:45.667+0000] {processor.py:157} INFO - Started process (PID=24883) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:07:45.673+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:07:45.675+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:07:45.674+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:07:46.757+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:07:46.734+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:07:46.759+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:07:46.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 1.142 seconds
[2023-08-29T22:08:16.945+0000] {processor.py:157} INFO - Started process (PID=24939) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:08:16.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:08:16.949+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:08:16.948+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:08:17.578+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:08:17.575+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:08:17.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:08:17.600+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.660 seconds
[2023-08-29T22:08:47.762+0000] {processor.py:157} INFO - Started process (PID=24996) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:08:47.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:08:47.765+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:08:47.765+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:08:48.212+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:08:48.206+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:08:48.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:08:48.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.483 seconds
[2023-08-29T22:09:19.099+0000] {processor.py:157} INFO - Started process (PID=25054) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:09:19.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:09:19.103+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:09:19.102+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:09:19.523+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:09:19.518+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:09:19.523+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:09:19.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.454 seconds
[2023-08-29T22:09:50.051+0000] {processor.py:157} INFO - Started process (PID=25111) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:09:50.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:09:50.055+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:09:50.054+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:09:50.568+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:09:50.564+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:09:50.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:09:50.600+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.554 seconds
[2023-08-29T22:10:21.210+0000] {processor.py:157} INFO - Started process (PID=25168) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:10:21.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:10:21.212+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:10:21.212+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:10:21.556+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:10:21.552+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:10:21.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:10:21.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.374 seconds
[2023-08-29T22:10:52.158+0000] {processor.py:157} INFO - Started process (PID=25225) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:10:52.160+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:10:52.161+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:10:52.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:10:52.525+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:10:52.521+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:10:52.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:10:52.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.393 seconds
[2023-08-29T22:11:22.928+0000] {processor.py:157} INFO - Started process (PID=25282) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:11:22.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:11:22.932+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:11:22.932+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:11:23.380+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:11:23.375+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:11:23.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:11:23.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.483 seconds
[2023-08-29T22:11:53.631+0000] {processor.py:157} INFO - Started process (PID=25339) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:11:53.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:11:53.635+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:11:53.635+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:11:54.169+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:11:54.164+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:11:54.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:11:54.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.574 seconds
[2023-08-29T22:12:24.296+0000] {processor.py:157} INFO - Started process (PID=25396) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:12:24.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:12:24.300+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:12:24.300+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:12:24.901+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:12:24.896+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:12:24.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:12:24.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.640 seconds
[2023-08-29T22:12:55.236+0000] {processor.py:157} INFO - Started process (PID=25454) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:12:55.239+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:12:55.242+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:12:55.241+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:12:55.904+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:12:55.897+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:12:55.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:12:55.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.778 seconds
[2023-08-29T22:13:26.288+0000] {processor.py:157} INFO - Started process (PID=25518) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:13:26.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:13:26.291+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:13:26.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:13:26.749+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:13:26.744+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:13:26.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:13:26.774+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.491 seconds
[2023-08-29T22:13:57.135+0000] {processor.py:157} INFO - Started process (PID=25575) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:13:57.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:13:57.139+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:13:57.138+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:13:57.566+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:13:57.561+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:13:57.567+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:13:57.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.465 seconds
[2023-08-29T22:14:27.894+0000] {processor.py:157} INFO - Started process (PID=25632) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:14:27.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:14:27.897+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:14:27.896+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:14:28.357+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:14:28.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:14:28.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:14:28.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.496 seconds
[2023-08-29T22:14:59.324+0000] {processor.py:157} INFO - Started process (PID=25689) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:14:59.325+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:14:59.327+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:14:59.326+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:14:59.826+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:14:59.821+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:14:59.827+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:14:59.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.535 seconds
[2023-08-29T22:15:29.989+0000] {processor.py:157} INFO - Started process (PID=25746) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:15:29.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:15:29.993+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:15:29.992+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:15:30.415+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:15:30.411+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:15:30.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:15:30.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.456 seconds
[2023-08-29T22:16:00.546+0000] {processor.py:157} INFO - Started process (PID=25803) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:16:00.548+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:16:00.549+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:16:00.549+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:16:00.936+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:16:00.931+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:16:00.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:16:00.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.419 seconds
[2023-08-29T22:16:31.782+0000] {processor.py:157} INFO - Started process (PID=25860) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:16:31.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:16:31.785+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:16:31.785+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:16:32.213+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:16:32.209+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:16:32.215+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:16:32.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.462 seconds
[2023-08-29T22:17:03.125+0000] {processor.py:157} INFO - Started process (PID=25917) to work on /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:17:03.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sensor_plot_dag.py for tasks to queue
[2023-08-29T22:17:03.128+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:17:03.128+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:17:03.474+0000] {logging_mixin.py:151} INFO - [2023-08-29T22:17:03.470+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/sensor_plot_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_plot_dag.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-08-29T22:17:03.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_plot_dag.py
[2023-08-29T22:17:03.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sensor_plot_dag.py took 0.376 seconds
